# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top/top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_sha256_ctrl_axi_0/top_sha256_ctrl_axi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_sha256_ctrl_axi_0 || ORIG_REF_NAME==top_sha256_ctrl_axi_0} -quiet] -quiet

# IP: bd/top/ip/top_ps7_0/top_ps7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_ps7_0 || ORIG_REF_NAME==top_ps7_0} -quiet] -quiet

# IP: bd/top/ip/top_ps7_axi_periph_0/top_ps7_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_ps7_axi_periph_0 || ORIG_REF_NAME==top_ps7_axi_periph_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_ps7_100M_0/top_rst_ps7_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_rst_ps7_100M_0 || ORIG_REF_NAME==top_rst_ps7_100M_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_0/top_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_auto_pc_0 || ORIG_REF_NAME==top_auto_pc_0} -quiet] -quiet

# XDC: bd/top/top_ooc.xdc
